import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <>
          <section className="wrapper bg-light">
            <div className="container py-14 py-md-16">
              <div className="row">
                <div className="col-lg-8 col-xl-7 col-xxl-6">
                  <h2 className="fs-15 text-uppercase text-muted mb-3">
                    What We Do?
                  </h2>
                  <h3 className="display-4 mb-9">
                    The service we offer is specifically designed to meet your
                    needs.
                  </h3>
                </div>
                {/* /column */}
              </div>
              {/* /.row */}
              <div className="row gx-md-8 gy-8">
                <div className="col-md-6 col-lg-3">
                  <div className="icon btn btn-block btn-lg btn-soft-yellow disabled mb-5">
                    {" "}
                    <i className="uil uil-phone-volume" />{" "}
                  </div>
                  <h4>24/7 Support</h4>
                  <p className="mb-3">
                    Nulla vitae elit libero, a pharetra augue. Donec id elit non
                    mi porta gravida at eget metus. Cras justo.
                  </p>
                  <a href="#" className="more hover link-yellow">
                    Learn More
                  </a>
                </div>
                {/*/column */}
                <div className="col-md-6 col-lg-3">
                  <div className="icon btn btn-block btn-lg btn-soft-red disabled mb-5">
                    {" "}
                    <i className="uil uil-shield-exclamation" />{" "}
                  </div>
                  <h4>Secure Payments</h4>
                  <p className="mb-3">
                    Nulla vitae elit libero, a pharetra augue. Donec id elit non
                    mi porta gravida at eget metus. Cras justo.
                  </p>
                  <a href="#" className="more hover link-red">
                    Learn More
                  </a>
                </div>
                {/*/column */}
                <div className="col-md-6 col-lg-3">
                  <div className="icon btn btn-block btn-lg btn-soft-leaf disabled mb-5">
                    {" "}
                    <i className="uil uil-laptop-cloud" />{" "}
                  </div>
                  <h4>Daily Updates</h4>
                  <p className="mb-3">
                    Nulla vitae elit libero, a pharetra augue. Donec id elit non
                    mi porta gravida at eget metus. Cras justo.
                  </p>
                  <a href="#" className="more hover link-leaf">
                    Learn More
                  </a>
                </div>
                {/*/column */}
                <div className="col-md-6 col-lg-3">
                  <div className="icon btn btn-block btn-lg btn-soft-blue disabled mb-5">
                    {" "}
                    <i className="uil uil-chart-line" />{" "}
                  </div>
                  <h4>Market Research</h4>
                  <p className="mb-3">
                    Nulla vitae elit libero, a pharetra augue. Donec id elit non
                    mi porta gravida at eget metus. Cras justo.
                  </p>
                  <a href="#" className="more hover link-blue">
                    Learn More
                  </a>
                </div>
                {/*/column */}
              </div>
              {/*/.row */}
            </div>
            {/* /.container */}
          </section>
          {/* /section */}
        </>
      </main>

    
    </div>
  );
};

export default Home;
